import type { Metadata } from "next";
import "./globals.css";

import { Dosis } from 'next/font/google';

const dosis = Dosis({
  subsets: ['latin'], 
  weight: ['200','300', '400', '500', '600', '700', '800'], 
  variable: '--font-dosis',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dosis.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
